version: '3'

services:
  reverse-proxy:
    image: traefik:latest # Official docker image for Traefik
    command: --api # Enables Traefik web UI
    container_name: "traefik"
    ports:
      - "80:80"     # HTTP port 80
      - "8080:8080" # Traefik Web UI port (enabled by --api)
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock # Allows Traefik to listen to docker events
      - ./traefik.toml:/etc/traefik/traefik.toml
  # ...
  nginx:
    image: nginx:latest
    container_name: nginx
